### ISSUE TITLE
duplicate message err

### ISSUE THREAD

**Issue by veo** [mosajjal/dnsconn#1]
example code change 

```
	for i := 0; i <= 5; i++ {
		_, err := dnstConn.Write([]byte("Hello TCP Server\n"))
		if err != nil {
			fmt.Printf("Error: %s\n", err)
		}
	}
```

will get duplicate message err,and client get just one msg

2024/01/07 22:48:45 ERROR failed to send question error="error in decrypting incoming packet from server: duplicate message"
> Hello TCP Client

**Comment by mosajjal** [comment]
test the latest commit please
