### ISSUE TITLE
index out of range [0] with length 0

### ISSUE THREAD

**Issue by veo** [mosajjal/dnsconn#2]
[index out of range [0] with length 0](panic: runtime error: index out of range [0] with length 0)

dnsconn.(*Server).handleServerToClient(0xc00090a070, {0x10ae8c240, 0xc00098a400}, 0xc0009a6cf0, {0xc0007e4ee0, {0x659abc1c, 0x0, 0xb219, 0xe, 0x5, ...}})
dnsconn/server.go:185 +0x45b
dnsconn/server.go:125 +0x253

**Comment by mosajjal** [comment]
test the latest commit please
